# Generated by Django 4.2 on 2025-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(upload_to='thumbnails/')),
                ('language', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
