# Generated by Django 4.2 on 2025-09-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_watchlater_watchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchhistory',
            name='watched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'movie')},
        ),
    ]
